import type { SoxxHolding } from './soxxHoldings'

export const SOXX_HOLDINGS_SNAPSHOT_AS_OF = '2026-04-29'
export const SOXX_HOLDINGS_SNAPSHOT_DOWNLOAD_DATE = '2026-04-30'
export const SOXX_HOLDINGS_SNAPSHOT_SOURCE = 'Official iShares SOXX fund data download'

export const SELECTED_SOXX_BUCKET_IDS = [
  'ai_compute',
  'memory',
  'equipment',
  'foundry_packaging',
] as const

export const SOXX_SELECTED_INTERNAL_BUCKET_IDS = SELECTED_SOXX_BUCKET_IDS

const OFFICIAL_SOXX_SOURCE_NOTE =
  `${SOXX_HOLDINGS_SNAPSHOT_SOURCE}; holdings as of ${SOXX_HOLDINGS_SNAPSHOT_AS_OF}; downloaded ${SOXX_HOLDINGS_SNAPSHOT_DOWNLOAD_DATE}.`

// Static equity holdings snapshot from the official iShares fund data download.
// Cash and derivative rows from the workbook are excluded from this equity snapshot.
export const SOXX_HOLDINGS_SNAPSHOT: SoxxHolding[] = [
  {
    ticker: 'AVGO',
    name: 'BROADCOM INC',
    weightPct: 7.91532,
    bucketId: 'ai_compute',
    driverClass: 'internal_driver',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'MU',
    name: 'MICRON TECHNOLOGY INC',
    weightPct: 7.8414,
    bucketId: 'memory',
    driverClass: 'internal_driver',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'AMD',
    name: 'ADVANCED MICRO DEVICES INC',
    weightPct: 7.83136,
    bucketId: 'ai_compute',
    driverClass: 'internal_driver',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'NVDA',
    name: 'NVIDIA CORP',
    weightPct: 7.36537,
    bucketId: 'ai_compute',
    driverClass: 'internal_driver',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'INTC',
    name: 'INTEL CORPORATION CORP',
    weightPct: 6.47822,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'MRVL',
    name: 'MARVELL TECHNOLOGY INC',
    weightPct: 5.97634,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'AMAT',
    name: 'APPLIED MATERIAL INC',
    weightPct: 4.77953,
    bucketId: 'equipment',
    driverClass: 'internal_driver',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'MPWR',
    name: 'MONOLITHIC POWER SYSTEMS INC',
    weightPct: 4.1666,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'NXPI',
    name: 'NXP SEMICONDUCTORS NV',
    weightPct: 3.97343,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'TXN',
    name: 'TEXAS INSTRUMENT INC',
    weightPct: 3.95805,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'KLAC',
    name: 'KLA CORP',
    weightPct: 3.71497,
    bucketId: 'equipment',
    driverClass: 'internal_driver',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'QCOM',
    name: 'QUALCOMM INC',
    weightPct: 3.41752,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'ADI',
    name: 'ANALOG DEVICES INC',
    weightPct: 3.41223,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'LRCX',
    name: 'LAM RESEARCH CORP',
    weightPct: 3.31654,
    bucketId: 'equipment',
    driverClass: 'internal_driver',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'MCHP',
    name: 'MICROCHIP TECHNOLOGY INC',
    weightPct: 3.08366,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'TSM',
    name: 'TAIWAN SEMICONDUCTOR MANUFACTURING',
    weightPct: 3.00755,
    bucketId: 'foundry_packaging',
    driverClass: 'internal_driver',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'TER',
    name: 'TERADYNE INC',
    weightPct: 2.98493,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'ASML',
    name: 'ASML HOLDING ADR REPRESENTING NV',
    weightPct: 2.74916,
    bucketId: 'equipment',
    driverClass: 'internal_driver',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'ON',
    name: 'ON SEMICONDUCTOR CORP',
    weightPct: 2.49813,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'CRDO',
    name: 'CREDO TECHNOLOGY GROUP HOLDING LTD',
    weightPct: 1.83114,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'ALAB',
    name: 'ASTERA LABS INC',
    weightPct: 1.72376,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'ENTG',
    name: 'ENTEGRIS INC',
    weightPct: 1.4533,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'MTSI',
    name: 'MACOM TECHNOLOGY SOLUTIONS INC',
    weightPct: 1.16645,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'NVMI',
    name: 'NOVA LTD',
    weightPct: 1.02829,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'ASX',
    name: 'ASE TECHNOLOGY HOLDING ADR REPRESE',
    weightPct: 1.01479,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'RMBS',
    name: 'RAMBUS INC',
    weightPct: 0.77377,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'STM',
    name: 'STMICROELECTRONICS ADR NV',
    weightPct: 0.68455,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'SWKS',
    name: 'SKYWORKS SOLUTIONS INC',
    weightPct: 0.60484,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'UMC',
    name: 'UNITED MICRO ELECTRONICS ADR REP',
    weightPct: 0.58808,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
  {
    ticker: 'ARM',
    name: 'ARM HOLDINGS AMERICAN DEPOSITARY S',
    weightPct: 0.55306,
    bucketId: null,
    driverClass: 'residual',
    asOfDate: SOXX_HOLDINGS_SNAPSHOT_AS_OF,
    sourceNote: OFFICIAL_SOXX_SOURCE_NOTE,
  },
]
